### ISSUE TITLE
Error when importing wiringpi2

### ISSUE THREAD

**Issue by DJManas** [BPI-SINOVOIP/BPI-WiringPi2-Python#2]
Clean install on Bananian and M1+, when tried to test, this error occurs

```
import wiringpi2
Traceback (most recent call last):
  File "/home/djmanas/BPI-WiringPi2-Python/wiringpi2.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_wiringpi2', [dirname(__file__)])
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named ‚_wiringpi2‘

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/djmanas/BPI-WiringPi2-Python/wiringpi2.py", line 28, in <module>
    _wiringpi2 = swig_import_helper()
  File "/home/djmanas/BPI-WiringPi2-Python/wiringpi2.py", line 20, in swig_import_helper
    import _wiringpi2
ImportError: /usr/local/lib/python3.4/dist-packages/wiringpi2-1.1.1-py3.4-linux-armv7l.egg/_wiringpi2.cpython-34m.so: undefined symbol: PyString_FromStringAndSize
```

**Comment by DJManas** [comment]
```
djmanas@Quirm ~/BPI-WiringPi2-Python $ uname -a
Linux Quirm 3.4.108-bananian #2 SMP PREEMPT Thu Aug 13 06:08:25 UTC 2015 armv7l GNU/Linux
```

```
djmanas@Quirm ~/BPI-WiringPi2-Python $ python3 --version
Python 3.4.2
```

Bananian 15.08 (Jessie)

**Comment by DJManas** [comment]
Only under python3, 2.7 is OK, but I take 2.7 python as obsolete
